import {
  ADMIN_LIST_EMPHASIZED_HEADER,
  ADMIN_LIST_ROW_CLASS,
  USER_LIST_CELL_CLASS,
  USER_LIST_DATE_CELL,
  USER_LIST_TIME_CELL,
  USER_LIST_TRAILING_CELL,
  buildAdminListHeaderClass,
  buildAdminListTableClass,
} from "@/components/admin/admin-list-table-layout";

const FINANCE_PAYMENTS_GRID_CLASS =
  "md:grid-cols-[minmax(0,1.1fr)_minmax(0,auto)_minmax(0,auto)_minmax(0,auto)_auto_auto_auto]";

export const ADMIN_FINANCE_PAYMENTS_LIST_TABLE_CLASS = buildAdminListTableClass(
  FINANCE_PAYMENTS_GRID_CLASS,
);

export const ADMIN_FINANCE_PAYMENTS_LIST_HEADER_CLASS = buildAdminListHeaderClass();

export const ADMIN_FINANCE_PAYMENTS_LIST_ROW_CLASS = ADMIN_LIST_ROW_CLASS;

export const ADMIN_FINANCE_PAYMENTS_LIST_CELL = USER_LIST_CELL_CLASS;

export const ADMIN_FINANCE_PAYMENTS_LIST_DATE_CELL = USER_LIST_DATE_CELL;

export const ADMIN_FINANCE_PAYMENTS_LIST_TIME_CELL = USER_LIST_TIME_CELL;

export const ADMIN_FINANCE_PAYMENTS_LIST_STATUS_CELL = USER_LIST_TRAILING_CELL;

export const ADMIN_FINANCE_PAYMENTS_LIST_SOURCE_CELL = USER_LIST_TRAILING_CELL;

export const ADMIN_FINANCE_PAYMENTS_LIST_METHOD_CELL = USER_LIST_TRAILING_CELL;

export const ADMIN_FINANCE_PAYMENTS_LIST_EMPHASIZED_HEADER = ADMIN_LIST_EMPHASIZED_HEADER;
