import {
  ADMIN_LIST_EMPHASIZED_HEADER,
  ADMIN_LIST_ROW_ACTIONS_HOVER_REVEAL,
  ADMIN_LIST_ROW_CLASS,
  USER_LIST_ACTIONS_CELL,
  USER_LIST_CELL_CLASS,
  USER_LIST_SPACER_CELL,
  USER_LIST_TRAILING_CELL,
  USER_LIST_TRAILING_HEADER_CELL,
  buildAdminListHeaderClass,
  buildAdminListTableClass,
} from "@/components/admin/admin-list-table-layout";

const GIFT_CARDS_GRID_CLASS =
  "md:grid-cols-[minmax(0,auto)_minmax(0,auto)_auto_auto_auto_auto_1fr_auto]";

export const ADMIN_GIFT_CARDS_LIST_TABLE_CLASS = buildAdminListTableClass(GIFT_CARDS_GRID_CLASS);

export const ADMIN_GIFT_CARDS_LIST_HEADER_CLASS = buildAdminListHeaderClass();

export const ADMIN_GIFT_CARDS_LIST_ROW_CLASS = ADMIN_LIST_ROW_CLASS;

export const ADMIN_GIFT_CARDS_LIST_ROW_ACTIONS_HOVER_REVEAL = ADMIN_LIST_ROW_ACTIONS_HOVER_REVEAL;

export const ADMIN_GIFT_CARDS_LIST_CELL = USER_LIST_CELL_CLASS;

export const ADMIN_GIFT_CARDS_LIST_STATUS_CELL = USER_LIST_TRAILING_CELL;

export const ADMIN_GIFT_CARDS_LIST_ACTIONS_CELL = USER_LIST_ACTIONS_CELL;

export const ADMIN_GIFT_CARDS_LIST_ACTIONS_HEADER_CELL = USER_LIST_TRAILING_HEADER_CELL;

export const ADMIN_GIFT_CARDS_LIST_SPACER_CELL = USER_LIST_SPACER_CELL;

export const ADMIN_GIFT_CARDS_LIST_EMPHASIZED_HEADER = ADMIN_LIST_EMPHASIZED_HEADER;
