import {
  ADMIN_LIST_EMPHASIZED_HEADER,
  ADMIN_LIST_ROW_ACTIONS_HOVER_REVEAL,
  ADMIN_LIST_ROW_CLASS,
  USER_LIST_ACTIONS_CELL,
  USER_LIST_CELL_CLASS,
  USER_LIST_SPACER_CELL,
  USER_LIST_TRAILING_HEADER_CELL,
  buildAdminListHeaderClass,
  buildAdminListTableClass,
} from "@/components/admin/admin-list-table-layout";

const CLIENTS_GRID_CLASS =
  "md:grid-cols-[minmax(0,1fr)_minmax(9.5rem,auto)_minmax(9.5rem,auto)_minmax(4.5rem,auto)_1fr_auto]";

export const ADMIN_CLIENTS_LIST_TABLE_CLASS = buildAdminListTableClass(CLIENTS_GRID_CLASS);

export const ADMIN_CLIENTS_LIST_HEADER_CLASS = buildAdminListHeaderClass();

export const ADMIN_CLIENTS_LIST_ROW_CLASS = ADMIN_LIST_ROW_CLASS;

export const ADMIN_CLIENTS_LIST_ROW_ACTIONS_HOVER_REVEAL = ADMIN_LIST_ROW_ACTIONS_HOVER_REVEAL;

export const ADMIN_CLIENTS_LIST_CELL = USER_LIST_CELL_CLASS;

export const ADMIN_CLIENTS_LIST_DATE_CELL = `${USER_LIST_CELL_CLASS} tabular-nums`;

export const ADMIN_CLIENTS_LIST_NOTES_CELL = `${USER_LIST_CELL_CLASS} tabular-nums md:justify-self-start`;

export const ADMIN_CLIENTS_LIST_ACTIONS_CELL = USER_LIST_ACTIONS_CELL;

export const ADMIN_CLIENTS_LIST_ACTIONS_HEADER_CELL = USER_LIST_TRAILING_HEADER_CELL;

export const ADMIN_CLIENTS_LIST_SPACER_CELL = USER_LIST_SPACER_CELL;

export const ADMIN_CLIENTS_LIST_EMPHASIZED_HEADER = ADMIN_LIST_EMPHASIZED_HEADER;
