import {
  ADMIN_LIST_EMPHASIZED_HEADER,
  ADMIN_LIST_ROW_ACTIONS_HOVER_REVEAL,
  ADMIN_LIST_ROW_CLASS,
  USER_LIST_ACTIONS_CELL,
  USER_LIST_CELL_CLASS,
  USER_LIST_DATE_CELL,
  USER_LIST_SPACER_CELL,
  USER_LIST_TRAILING_HEADER_CELL,
  buildAdminListHeaderClass,
  buildAdminListTableClass,
} from "@/components/admin/admin-list-table-layout";

const FINANCE_USER_GRID_CLASS =
  "md:grid-cols-[minmax(0,1.1fr)_minmax(0,0.9fr)_auto_auto_auto_auto_1fr_auto]";

export const ADMIN_FINANCE_USER_LIST_TABLE_CLASS = buildAdminListTableClass(FINANCE_USER_GRID_CLASS);

export const ADMIN_FINANCE_USER_LIST_HEADER_CLASS = buildAdminListHeaderClass();

export const ADMIN_FINANCE_USER_LIST_ROW_CLASS = ADMIN_LIST_ROW_CLASS;

export const ADMIN_FINANCE_USER_LIST_ROW_ACTIONS_HOVER_REVEAL = ADMIN_LIST_ROW_ACTIONS_HOVER_REVEAL;

export const ADMIN_FINANCE_USER_LIST_CELL = USER_LIST_CELL_CLASS;

export const ADMIN_FINANCE_USER_LIST_DATE_CELL = USER_LIST_DATE_CELL;

export const ADMIN_FINANCE_USER_LIST_ACTIONS_CELL = USER_LIST_ACTIONS_CELL;

export const ADMIN_FINANCE_USER_LIST_ACTIONS_HEADER_CELL = USER_LIST_TRAILING_HEADER_CELL;

export const ADMIN_FINANCE_USER_LIST_SPACER_CELL = USER_LIST_SPACER_CELL;

export const ADMIN_FINANCE_USER_LIST_EMPHASIZED_HEADER = ADMIN_LIST_EMPHASIZED_HEADER;

/** Coach · Earnings · Sessions · Month · Payout — five equal tracks. */
const FINANCE_COACH_GRID_CLASS = "md:grid-cols-[repeat(5,minmax(0,1fr))]";

export const ADMIN_FINANCE_COACH_LIST_TABLE_CLASS = buildAdminListTableClass(FINANCE_COACH_GRID_CLASS);

export const ADMIN_FINANCE_COACH_LIST_HEADER_CLASS = buildAdminListHeaderClass();

export const ADMIN_FINANCE_COACH_LIST_ROW_CLASS = ADMIN_LIST_ROW_CLASS;

export const ADMIN_FINANCE_COACH_LIST_HEADER_CELL = "min-w-0";

export const ADMIN_FINANCE_COACH_LIST_COACH_CELL = USER_LIST_CELL_CLASS;

export const ADMIN_FINANCE_COACH_LIST_MONEY_CELL = `${USER_LIST_CELL_CLASS} tabular-nums`;

export const ADMIN_FINANCE_COACH_LIST_SESSIONS_CELL = [
  USER_LIST_CELL_CLASS,
  "tabular-nums md:flex md:items-center",
].join(" ");

export const ADMIN_FINANCE_COACH_LIST_MONTH_CELL = `${USER_LIST_CELL_CLASS} tabular-nums`;

export const ADMIN_FINANCE_COACH_LIST_PAYOUT_CELL = [
  USER_LIST_CELL_CLASS,
  "md:flex md:items-center",
].join(" ");

export const ADMIN_FINANCE_COACH_LIST_EMPHASIZED_HEADER = ADMIN_LIST_EMPHASIZED_HEADER;

const NOTIFICATIONS_GRID_CLASS =
  "md:grid-cols-[minmax(0,auto)_minmax(0,1.2fr)_minmax(0,1fr)_auto_auto_auto]";

export const ADMIN_NOTIFICATIONS_LIST_TABLE_CLASS = buildAdminListTableClass(NOTIFICATIONS_GRID_CLASS);

export const ADMIN_NOTIFICATIONS_LIST_HEADER_CLASS = buildAdminListHeaderClass();

export const ADMIN_NOTIFICATIONS_LIST_ROW_CLASS = ADMIN_LIST_ROW_CLASS;

export const ADMIN_NOTIFICATIONS_LIST_CELL = USER_LIST_CELL_CLASS;

export const ADMIN_NOTIFICATIONS_LIST_EMPHASIZED_HEADER = ADMIN_LIST_EMPHASIZED_HEADER;

const NOTIFICATIONS_SCHEDULED_GRID_CLASS =
  "md:grid-cols-[minmax(0,1.2fr)_auto_auto_auto_auto_1fr_auto]";

export const ADMIN_NOTIFICATIONS_SCHEDULED_LIST_TABLE_CLASS = buildAdminListTableClass(
  NOTIFICATIONS_SCHEDULED_GRID_CLASS,
);

export const ADMIN_NOTIFICATIONS_SCHEDULED_LIST_HEADER_CLASS = buildAdminListHeaderClass();

export const ADMIN_NOTIFICATIONS_SCHEDULED_LIST_ROW_CLASS = ADMIN_LIST_ROW_CLASS;

export const ADMIN_NOTIFICATIONS_SCHEDULED_LIST_CELL = USER_LIST_CELL_CLASS;

export const ADMIN_NOTIFICATIONS_SCHEDULED_LIST_ROW_ACTIONS_HOVER_REVEAL =
  ADMIN_LIST_ROW_ACTIONS_HOVER_REVEAL;

export const ADMIN_NOTIFICATIONS_SCHEDULED_LIST_ACTIONS_CELL = USER_LIST_ACTIONS_CELL;

export const ADMIN_NOTIFICATIONS_SCHEDULED_LIST_SPACER_CELL = USER_LIST_SPACER_CELL;

export const ADMIN_NOTIFICATIONS_SCHEDULED_LIST_EMPHASIZED_HEADER = ADMIN_LIST_EMPHASIZED_HEADER;
