export const SESSION_REVIEW_PROMPT_TTL_DAYS = 7;
export const SESSION_REVIEW_RATING_MIN = 1;
export const SESSION_REVIEW_RATING_MAX = 5;
export const SESSION_REVIEW_COMMENT_MAX = 2000;
export const SESSION_REVIEW_INBOX_TAKE = 15;
export const SESSION_REVIEW_HEADER_PREVIEW = 4;
export const SESSION_REVIEW_PENDING_TAKE = 20;
