export const ACTION_BROADCAST = 'NOTIFICATION_BROADCAST';
export const ACTION_NOTIFICATION_DELIVERY = 'NOTIFICATION_DELIVERY';
export const ACTION_BROADCAST_SCHEDULED = 'NOTIFICATION_BROADCAST_SCHEDULED';
export const ACTION_BROADCAST_SCHEDULED_UPDATED =
  'NOTIFICATION_BROADCAST_SCHEDULED_UPDATED';
export const ACTION_BROADCAST_SCHEDULED_CANCELLED =
  'NOTIFICATION_BROADCAST_SCHEDULED_CANCELLED';
export const ACTION_BROADCAST_SCHEDULED_SENT =
  'NOTIFICATION_BROADCAST_SCHEDULED_SENT';
export const ACTION_BROADCAST_SCHEDULED_FAILED =
  'NOTIFICATION_BROADCAST_SCHEDULED_FAILED';

export const SCHEDULED_TIMELINE_ACTIONS = [
  ACTION_BROADCAST_SCHEDULED_UPDATED,
  ACTION_BROADCAST_SCHEDULED_CANCELLED,
  ACTION_BROADCAST_SCHEDULED_SENT,
  ACTION_BROADCAST_SCHEDULED_FAILED,
] as const;

export const REMINDER_HOURS_BEFORE = 2;
export const ENABLE_BACKGROUND_REMINDERS_ENV = 'ENABLE_BACKGROUND_REMINDERS';
