import {
  ADMIN_LIST_EMPHASIZED_HEADER,
  ADMIN_LIST_ROW_ACTIONS_HOVER_REVEAL,
  ADMIN_LIST_ROW_CLASS,
  USER_LIST_ACTIONS_CELL,
  USER_LIST_CELL_CLASS,
  USER_LIST_DATE_CELL,
  USER_LIST_SPACER_CELL,
  USER_LIST_TRAILING_HEADER_CELL,
  buildAdminListHeaderClass,
  buildAdminListTableClass,
} from "@/components/admin/admin-list-table-layout";

const CONTENT_POSTS_GRID_CLASS =
  "md:grid-cols-[minmax(0,auto)_minmax(0,1.4fr)_minmax(7rem,auto)_minmax(7rem,auto)_minmax(9rem,auto)_1fr_auto]";

/** Posts per page on Admin / Manager / Content Admin lists. */
export const CONTENT_POSTS_LIST_PAGE_SIZE = 10;

export const CONTENT_POSTS_LIST_TABLE_CLASS = buildAdminListTableClass(CONTENT_POSTS_GRID_CLASS);

export const CONTENT_POSTS_LIST_HEADER_CLASS = buildAdminListHeaderClass();

export const CONTENT_POSTS_LIST_ROW_CLASS = ADMIN_LIST_ROW_CLASS;

export const CONTENT_POSTS_LIST_ROW_ACTIONS_HOVER_REVEAL = ADMIN_LIST_ROW_ACTIONS_HOVER_REVEAL;

export const CONTENT_POSTS_LIST_CELL = USER_LIST_CELL_CLASS;

export const CONTENT_POSTS_LIST_DATE_CELL = USER_LIST_DATE_CELL;

export const CONTENT_POSTS_LIST_ACTIONS_CELL = USER_LIST_ACTIONS_CELL;

export const CONTENT_POSTS_LIST_ACTIONS_HEADER_CELL = USER_LIST_TRAILING_HEADER_CELL;

export const CONTENT_POSTS_LIST_SPACER_CELL = USER_LIST_SPACER_CELL;

export const CONTENT_POSTS_LIST_EMPHASIZED_HEADER = ADMIN_LIST_EMPHASIZED_HEADER;
