import {
  USER_LIST_ACTIONS_CELL,
  USER_LIST_CLASS_CELL,
  USER_LIST_DATE_CELL,
  USER_LIST_ROW_CARD,
  USER_LIST_HEADER_SURFACE,
  USER_LIST_SPACER_CELL,
  USER_LIST_SPOTS_CELL,
  USER_LIST_TABLE_GRID_GAP,
  USER_LIST_TABLE_HEADER_PAD,
  USER_LIST_TABLE_HEADER_TEXT,
  USER_LIST_TABLE_ROW_PAD,
  USER_LIST_TIME_CELL,
  USER_SCHEDULE_LIST_GRID_COLS,
} from "@/components/account/user-list-table-layout";

export { USER_SCHEDULE_LIST_GRID_COLS };

export const USER_SCHEDULE_LIST_HEADER_CLASS = [
  "hidden",
  USER_LIST_HEADER_SURFACE,
  USER_LIST_TABLE_HEADER_PAD,
  USER_LIST_TABLE_HEADER_TEXT,
  "md:grid",
  USER_SCHEDULE_LIST_GRID_COLS,
  USER_LIST_TABLE_GRID_GAP,
  "md:items-end",
].join(" ");

export const USER_SCHEDULE_LIST_ROW_CLASS = [
  USER_LIST_ROW_CARD,
  "grid w-full grid-cols-1 gap-3 text-left",
  USER_LIST_TABLE_ROW_PAD,
  USER_SCHEDULE_LIST_GRID_COLS,
  USER_LIST_TABLE_GRID_GAP,
  "md:items-center md:gap-y-0",
].join(" ");

export {
  USER_LIST_ACTIONS_CELL as USER_SCHEDULE_LIST_ACTIONS_CLASS,
  USER_LIST_CLASS_CELL as USER_SCHEDULE_LIST_CLASS_CELL,
  USER_LIST_DATE_CELL as USER_SCHEDULE_LIST_DATE_CELL,
  USER_LIST_SPACER_CELL as USER_SCHEDULE_LIST_SPACER_CELL,
  USER_LIST_SPOTS_CELL as USER_SCHEDULE_LIST_SPOTS_CELL,
  USER_LIST_TIME_CELL as USER_SCHEDULE_LIST_TIME_CELL,
};
